### ISSUE TITLE
R1Q12 Diffraction pattern shift

### ISSUE THREAD

**Issue by dagewa** [dagewa/DIALS_for_ED_paper#24]
> Diffraction pattern shift is caused by beam shift in the imaging plane. If the beam shift is used for the crystal tracking, all diffraction patterns in a dataset will have their own diffraction shift – not necessarily behaving like a monotone function. (Back to the question – how were the patterns centered.) If the diffraction data was collected in SAED mode (was it?) or in nanodiffraciton (?) without additional beam shift during the acquisition (?), no continuous diffraction shift should be present in the data. If yet exists – it would be great to spot down the origin of it.

**Comment by dagewa** [comment]
No beam shift was used for crystal tracking. The data were collected using a beam with a diameter of about 1500 nm and continuous rotation of the crystal; we did not do selected area electron diffraction (SAED). Small amounts of beam drift were determined to be present for some datasets (up to ~2 px) as described in the answer to q6.

**Comment by tgruene** [comment]
I agree.
