### ISSUE TITLE
R2 chicken-and-egg

### ISSUE THREAD

**Issue by dagewa** [dagewa/DIALS_for_ED_paper#34]
> One aspect that would appear worth mentioning is the "chicken-and-egg" problem encountered when trying to establish the X- and Y- lens distortion tables and - at the same time - trying to index an unknown crystal. In this case, the RMSD values will be inflated (since without knowing the distortion, one must start with a flat distortion map) and will not allow to find the correct space group, nor the constraints on its axes and angles (as demanded by its Laue group). In consequence, it would be impossible to establish the distortion map. A similar chicken-and-egg problem occurs if the direction of rotation is unknown. The authors could explain that the description of a new experimental setup must undergo a bootstrap procedure, which solves the chicken-and-egg problems by starting from well-characterized experimental objects (e.g. insulin crystals and the like).

**Comment by dagewa** [comment]
@cmaxtb Perhaps this was touched on in your earlier paper? I would need to check again. The chicken-and-egg problem would be a theoretical concern _if_ a sample with unknown cell was being analysed and calibration was being done with the diffraction data from that sample alone. However, in practice the distortion map was determined using powder patterns from a known sample, and to date I think we have knowledge of the expected unit cell of the samples that have been analysed by ED. It is true though that these concerns should be addressed as ED moves from niche activity to a tool that might readily be applied to crystals with no prior expectation of the cell and space group

**Comment by cmaxtb** [comment]
Yes, the distortion map was based on a known aluminium diffraction standard. Calibration of the diffraction setup is something you should ideally always do using something well-known. We could changes the lines below to:

The \emph{datasets 2--7} of our examples all showed a significant elliptical
distortion. The parameters of this distortion were determined _using a well known
diffraction standar_d as described previously \cite{Clabbers2017}.

We also mention that:

Instruments used
for electron diffraction should therefore be well calibrated
\cite{gemmi_adt:2015}.

Maybe we can make this statement a bit clearer, or just mention it in the response.

**Comment by dagewa** [comment]
Reply:
We have made it clearer that in our case the distortion map was calculated based on an independent, well-known diffraction standard (thus avoiding the "chicken and egg" issue). We also noted that this is good practice and would become essential if ED were being used to analyse a sample of previously unknown unit cell.
