### ISSUE TITLE
R2 defn of R1

### ISSUE THREAD

**Issue by dagewa** [dagewa/DIALS_for_ED_paper#38]
> - Table 2: what is the definition of R1 ? Is that Rwork?

**Comment by dagewa** [comment]
We define Rcomplete in the footnote, but not R1.

TODO add definition of R1 to the footnote

**Comment by tgruene** [comment]
"$R1 = \frac{ \sum_{(hkl)} \left| |F_{obs}(hkl)| - |F_{calc}(hkl)|\right| } { \sum_{(hkl)} |F_{obs}(hkl)|} where the sum includes \emph{all} data."
It is usually added as footnote to Table 1, but this practice is sometimes forgotten.
