### ISSUE TITLE
Ewald sphere / experiment geometry figure

### ISSUE THREAD

**Issue by dagewa** [dagewa/DIALS_for_ED_paper#7]
> I have a very similar drawing to slide 23 in a review that JP and I submitted a few weeks back and got accepted, but we can anyhow include the Ewald sphere reconstruction shown on slides 21-22, and if you want it would also be fine to add in the real space drawing of slide 23. One of the referee’s specifically asked for a more detailed description of the electron diffraction geometry, so I guess it’s worthwhile to include such drawings in this manuscript because most readers will be X-ray crystallographers and are familiar with a rather different experimental setup.

**Comment by dagewa** [comment]
@cmaxtb perhaps we can just cite your review, as it is accepted, rather than making a new figure like slide 23? Including the Ewald sphere comparison to scale would still be useful I think. Tim also has a similar figure in some of his slides

**Comment by cmaxtb** [comment]
sure, it already has an doi so we can cite it, including the Ewald sphere drawings from 21 and 22 would still be worthwhile

**Comment by dagewa** [comment]
@cmaxtb can you please tell me the DOI of the review? I'll add the reference, cheers

**Comment by cmaxtb** [comment]
doi: 10.1080/0889311X.2018.1446427

**Comment by dagewa** [comment]
Ah it seems that is not active yet. I'll just make a note to check again later

**Comment by cmaxtb** [comment]
Yes it got already assigned a doi, it was accepted and should be online soon. If you want I can send you a preprint.

**Comment by dagewa** [comment]
Ok, thanks, that'll be good
